"""add openai_image_api_protocol to settings

Revision ID: 416cd372ad39
Revises: 819293cce08c
Create Date: 2026-04-27 02:39:29.870635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416cd372ad39'
down_revision = '819293cce08c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('openai_image_api_protocol', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'openai_image_api_protocol')
    # ### end Alembic commands ###



