"""add caption and original_filename to materials

Revision ID: c153f8c4e111
Revises: 9ad736fec43d
Create Date: 2026-03-07 16:40:18.053611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c153f8c4e111'
down_revision = '9ad736fec43d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('caption', sa.String(length=500), nullable=True))
    op.add_column('materials', sa.Column('original_filename', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'original_filename')
    op.drop_column('materials', 'caption')
    # ### end Alembic commands ###



